version: "3.1"
services:
    front:
        image: front
        build: ./front
        ports:
            - "5173:5173"
        depends_on:
            - back
            - database
    back:
        image: back
        build: ./back
        ports:
            - "3000:3000"
        depends_on:
            - database
    database:
        image: database
        build: ./database
        ports:
            - "8080:8080"
        volumes:
            - database:/pb/pb_data
networks:
    internal:
volumes:
    database:
