export type buildingType =
    | "titane_mine"
    | "copper_mine"
    | "silicium_mine"
    | "house"
    | "copper_factory"
    | "titane_factory"
    | "oil_well"
    | "oil_refinery"
    | "bio_refinery"
    | "bacterial_vat"
    | "electronic_factory"
    | "automatic_wood_chopper"
    | "compost"
    | "salt_mine"
    | "hydroponic_farm"
    | "life_incubator"
    | "food_processor"
    | "filter_factory"
    | "atmospheric_filter"
    |"town_hall"
    ;